### ISSUE TITLE
Add max traces and CPU/Memory Request/Limit parameters to all-in-one template

### ISSUE THREAD

**Issue by etoews** [jaegertracing/jaeger-openshift#101]
## Requirement - what kind of business use case are you trying to solve?

Over-utilization of CPU/Memory on a node are known to cause instability. Even in non-production OpenShift environments, guard rails on Jaeger are a requirement to prevent such instability.

We discovered this the hard way. 😉 

## Problem - what in Jaeger blocks you from solving the requirement?

Lack of parameters in the template for max traces and CPU/Memory Requests/Limits.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Add max traces and CPU/Memory Request/Limit parameters to the [all-in-one template](https://github.com/jaegertracing/jaeger-openshift/blob/master/all-in-one/jaeger-all-in-one-template.yml).

P.S. I'm not sure this even really falls under "significant changes" from [Making a Change](https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md#making-a-change) but I figured I'd create an issue for good measure. I'll follow it up with a PR immediately as it's pretty straight-forward.

**Comment by pavolloffay** [comment]
hi @etoews, I think we are going to deprecate this repository in favor of https://github.com/jaegertracing/jaeger-operator.

Have you tried to use operator?

**Comment by etoews** [comment]
@pavolloffay Nice! I confess I hadn't noticed that much less tried to use it yet.

That's something we'll definitely look at. In the meantime, it would be appreciated if we could move forward with this issue/PR, even though this repo may one day be deprecated.
