### ISSUE TITLE
Compile docker images myself

### ISSUE THREAD

**Issue by veterr** [jaegertracing/jaeger-openshift#106]
Hi, I was able to start the solution, but now I have to compile docker images from scratch myself, because otherwise the security in my organization will not allow us to use them :(
How can I find the Dockerfile-s that following images -
jaegertracing/jaeger-collector:1.8
jaegertracing/jaeger-query:1.8
jaegertracing/jaeger-agent:1.8
quay.io/pires/docker-elasticsearch-kubernetes:5.6.2 where compiled from?

**Comment by objectiser** [comment]
The docker images are built as part of the build/release process from this repo: https://github.com/jaegertracing/jaeger - the docker files are contained within the individual component folder, e.g. agent is https://github.com/jaegertracing/jaeger/blob/master/cmd/agent/Dockerfile

The other Dockerfile can be found here: https://github.com/pires/docker-elasticsearch-kubernetes
