### ISSUE TITLE
Provide an openshift.io template

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-openshift#12]
As discussed on #8 , the production template deploys the Agent as a daemon set, which requires cluster admin permissions. For openshift.io , the user deploying Jaeger probably won't be a cluster admin, so, the Agent has to deploy as a regular DC/RC. A new template is then required for that.

**Comment by pavolloffay** [comment]
It's already done in https://github.com/jaegertracing/jaeger-openshift/pull/35/
