### ISSUE TITLE
Production template has hard dependency on jaeger-infra namespace

### ISSUE THREAD

**Issue by kevinearls** [jaegertracing/jaeger-openshift#15]
I was trying to deploy jaeger using the production template as specified in the README under "Installing Jaeger on its own namespace as admin".  (NOTE: I'm using minishift 1.1.0 on Fedora 25, and was starting from scratch, having done: minishift stop, minishift delete, and then minishift start).

I did the following, as specified in the instructions:

oc login -u system:admin
oc new-project jaeger
oc process -f production//jaeger-production-template.yml | oc create -f -

This gave me:
Error from server (NotFound): namespaces "jaeger-infra" not found
Error from server (NotFound): namespaces "jaeger-infra" not found
Error from server (NotFound): namespaces "jaeger-infra" not found
Error from server (NotFound): namespaces "jaeger-infra" not found
Error from server (NotFound): namespaces "jaeger-infra" not found
Error from server (NotFound): namespaces "jaeger-infra" not found
Error from server (NotFound): namespaces "jaeger-infra" not found
Error from server (NotFound): namespaces "jaeger-infra" not found
Error from server (NotFound): namespaces "jaeger-infra" not found
Error from server (NotFound): namespaces "jaeger-infra" not found

**Comment by pavolloffay** [comment]
There is probably a bug in readme you should create `jaeger-infra` namespace.

**Comment by pavolloffay** [comment]
I'm going to open PR to simplify and fix it.

**Comment by kevinearls** [comment]
Cool, thanks.  I meant to mention I didn't know if it was a template problem or just a readme problem.

**Comment by kevinearls** [comment]
Hi @pavolloffay   I've tried this, and the first two cases ("Development setup" and "Production setup") worked fine, but I ran into a problem with "Install Jaeger as developer user".  I had done a minishift delete first, so I was starting from scratch.  The instructions say "note that namespace jaeger has been already created"  which I assume means this example expects the jaeger namespace has already been created.

I did not have a jaeger namespace, so I did "oc create namespace jaeger" after logging in as system:admin and before executing the other steps.

However when I tried the "oc process..." step as developer, I got a bunch of messages like "Error from server (Forbidden): User "developer" cannot create services in project "jaeger".

Does this mean this example assumes we already have a namespace called jaeger but it has to have been created by the developer?

**Comment by pavolloffay** [comment]
@kevinearls are you following steps from #16 ?

**Comment by kevinearls** [comment]
@pavolloffay yes, I was following the readme and using the code from the fix-readme branch on your fork

**Comment by pavolloffay** [comment]
What happened:
you have created `jaeger` namespace for system:admin, then you tried to create resources under developer which does not have access to that namespace..

I will add a note in readme.

**Comment by pavolloffay** [comment]
@kevinearls change is there let me know if it is better now.

**Comment by kevinearls** [comment]
@pavolloffay That works great.  Thanks!

**Comment by pavolloffay** [comment]
Closed via #16
