### ISSUE TITLE
Add contact information to README

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-openshift#18]
People should know how to get in touch should they need help in getting this up and running. Our README file could contain pointers, stating that we are available on Gitter, IRC, mailing list and so on.

**Comment by pavolloffay** [comment]
We should add travis and gitter badge.

**Comment by pavolloffay** [comment]
@jpkrohling can we close this? Users can report issues directly in the repo or contact via gitter channel.
