### ISSUE TITLE
UI error: NetworkError when attempting to fetch resource. 

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-openshift#20]
Steps to reproduce:

> oc cluster up
oc process -f https://raw.githubusercontent.com/jaegertracing/jaeger-openshift/master/all-in-one/jaeger-all-in-one-template.yml | oc create -f -

then try to open the URL in a browser: https://jaeger-query-myproject.127.0.0.1.nip.io/

![jaegerui-networkerror](https://user-images.githubusercontent.com/164562/27598138-75756564-5b5c-11e7-8338-28bc6c72a2b7.png)

The oc client version are:

> [gbrown@localhost openshift]$ oc version
oc v3.6.0-alpha.2+3c221d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO
Server https://127.0.0.1:8443
openshift v3.6.0-alpha.2+3c221d5
kubernetes v1.6.1+5115d708d7

**Comment by jpkrohling** [comment]
I just tried locally and it works:

```
oc version
oc v3.6.0-alpha.2+442a747-373
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.6.0-alpha.2+3c221d5
kubernetes v1.6.1+5115d708d7
```

Are you using Fedora's `docker`, or Docker Inc's?

**Comment by pavolloffay** [comment]
maybe `iptables -F` could fix it?

**Comment by objectiser** [comment]
Tried `iptables -F` and didn't work :(

I believe its docker inc's:

> [gbrown@localhost repositories]$ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64
Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64

**Comment by objectiser** [comment]
Appears to be a local issue in my environment - switching to use minishift instead fixed the problem.
