### ISSUE TITLE
Update JenkinsFile to wait until ElasticSearch or Cassandra is deployed before proceeding

### ISSUE THREAD

**Issue by kevinearls** [jaegertracing/jaeger-openshift#53]
Currently we have a race condition here as we may try to start Jaeger before the storage is ready. This is more of a problem with Cassandra as it takes longer to start. Typically Jaeger can deal with this but occasionally it causes test failures.

**Comment by pavolloffay** [comment]
@kevinearls is this still relevant?

**Comment by kevinearls** [comment]
@pavolloffay No, sorry I think I opened this in the wrong place.
