### ISSUE TITLE
All-in-one template does not expose 5778 by default

### ISSUE THREAD

**Issue by maximmold** [jaegertracing/jaeger-openshift#73]
I have a Spring boot based application that creates the Tracer bean with `Configuration.fromEnv().getTracer()`. I set the appropriate environment variables to point to the sampler manager, but by default I was getting no entries in the jaeger ui. I finally figured out that sampling was not happening presumably because the agent port 5778 was not being exposed by default. Once I exposed it, everything worked fine. I would think this example template would have this exposed by default and the instructions I've seen for running locally with docker expose this port by default. It feels like there should be a warning at the very least if the sample manager cannot be contacted and sampling is therefore disabled.

**Comment by maximmold** [comment]
Here is the file of concern: [https://github.com/jaegertracing/jaeger-openshift/blob/master/all-in-one/jaeger-all-in-one-template.yml](url)

**Comment by jpkrohling** [comment]
@maximmold would you be interested in contributing with a fix?

**Comment by maximmold** [comment]
Here's a pull request. Please do a squash commit on this.
https://github.com/jaegertracing/jaeger-openshift/pull/80
