### ISSUE TITLE
jaeger-agent service is not available in production template

### ISSUE THREAD

**Issue by jkandasa** [jaegertracing/jaeger-openshift#87]
## Requirement - what kind of business use case are you trying to solve?
I see OpenShift production template does not have `jaeger-agent` service.
It is inconsistent with the [Kubernetes production template](https://github.com/jaegertracing/jaeger-kubernetes/blob/master/jaeger-production-template.yml).

## Problem - what in Jaeger blocks you from solving the requirement?
There is no blockers.

**Comment by ofirattia** [comment]
the jaeger-agent should come as part of your deployment configuration and act a side-car container for your service.

**Comment by jpkrohling** [comment]
To complement @ofirattia's answer: it's inconsistent with the Kubernetes template because OpenShift requires cluster-admin to install a `DaemonSet` and the template is meant to be consumed by a non-privileged user.
