### ISSUE TITLE
Agent as sidecar - wrong deployment snippet in readme

### ISSUE THREAD

**Issue by fgiloux** [jaegertracing/jaeger-openshift#91]
Hi 

## Requirement - what kind of business use case are you trying to solve?
This is just about an error in the doc:
https://github.com/jaegertracing/jaeger-openshift

## Problem - what in Jaeger blocks you from solving the requirement?
An error in the doc. The sidecar container does not start

## Proposal - what do you suggest to solve the problem or improve the existing situation?
`command:
          - "--collector.host-port=jaeger-collector.jaeger-infra.svc:14267"`
should be replaced with (as in the Kubernetes readme):
`args:
            - '--collector.host-port=jaeger-collector.jaeger-infra.svc:14267'`

## Any open questions to address
I can create a pull request if that's of any help

Regards,

Frédéric

**Comment by jpkrohling** [comment]
Great catch, a recent change in the underlying image probably caused this. Would you mind sending a PR? IIRC, the `jaeger-query` service from the `production` template has an example of sidecar deployment (see #90)

**Comment by jpkrohling** [comment]
Closed by #94
