### ISSUE TITLE
Missing Variable in Cassanda production template

### ISSUE THREAD

**Issue by martin123218** [jaegertracing/jaeger-openshift#96]
Hi,

## Requirement - what kind of business use case are you trying to solve?
There is missing parameter in cassandra-production template
${REPLICA_COUNT} and the template fails.

## Problem - what in Jaeger blocks you from solving the requirement?
Nothing but template should be fixed

Regards,

Martin

**Comment by jpkrohling** [comment]
Nice catch! It should relatively easy to fix it: would you mind sending a PR?
